version: "3.9"

services:
  gateway:
    build: ./gateway
    ports:
      - "3000:3000"
    depends_on:
      - user
      - post

  user:
    build: ./user
    ports:
      - "3001:3001"
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=secret
      - DB_NAME=userdb
    depends_on:
      - mysql

  post:
    build: ./post
    ports:
      - "3002:3002"
    environment:
      - DB_HOST=mongodb  
      - DB_NAME=your-db-name
    depends_on:
      - mongodb

  mysql:
    image: mysql:8.0  
    container_name: mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - mysql-data:/var/lib/mysql

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mysql-data:
  mongo-data:
